# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bloggi', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
